### ISSUE TITLE
Unique indictor data not showing up on scheme snapshot

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#63]
![image](https://user-images.githubusercontent.com/64309749/211462932-c42adcd3-0975-4f5f-8836-32684308e51d.png)

Reproducible in any constituency

**Comment by arunsud** [comment]
In the above case, I've selected a unique indicator for MGNREGS but it's not showing up on the snapshot preview even when changing years or to other unique indicators.

**Comment by aashimgarg** [comment]
It is due to the wrong slugs used in ckan state files. 
For example Sakti , Chattisgarh

![Screenshot from 2023-01-10 11-05-22](https://user-images.githubusercontent.com/55639487/211470299-c6b2b902-d5c8-4d8c-850f-d12fc092d304.png)

![Screenshot from 2023-01-10 11-07-23](https://user-images.githubusercontent.com/55639487/211470312-22f4131a-69c7-4956-b009-d29a0c43f5b9.png)

CC @tauseefsshah

**Comment by tauseefsshah** [comment]
@arun I have fixed the issue in the data. Can you please verify if this issue is fixed?
